services:
  - type: web
    name: shl-ai-hiring-assistant
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    regions:
      - oregon
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash-lite
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /opt/render/project/src/.cache/sentence_transformers
